export const actionTypes = {
  SET_STUDENTS: "SET_STUDENTS",
  SET_STUDENTS_ID: "SET_STUDENTS_ID",
  SET_STUDENTS_PAGINATION: "SET_STUDENTS_PAGINATION",
  CREATE_STUDENTS: "CREATE_STUDENTS",
  DELETE_STUDENTS: "DELETE_STUDENTS",
};
