export const actionTypes = {
  GET_VEHICLES: 'GET_VEHICLES',
  GET_VEHICLES_ID: 'GET_VEHICLES_ID',
  GET_VEHICLES_PAGINATION: 'GET_VEHICLES_PAGINATION',
  EDIT_VEHICLES: 'EDIT_VEHICLES',
  CREATE_VEHICLES: 'CREATE_VEHICLES',
  DELETE_VEHICLES: 'DELETE_VEHICLES'
};
