export const actionTypes = {
  SET_ROUTES: "SET_ROUTES",
  SET_ALL_ROUTES: "SET_ALL_ROUTES",
  SET_ROUTE_ID: "SET_ROUTE_ID",
  CREATE_ROUTE: "CREATE_ROUTE",
  EDIT_ROUTE: "EDIT_ROUTE",
  DELETE_ROUTE: "DELETE_ROUTE",
  SET_ROUTE_PAGINATION: "SET_ROUTE_PAGINATION",
};
