export const actionTypes = {
  GET_ALL_PERMISSIONS: 'GET_ALL_PERMISSIONS',
  GET_PERMISSIONS: 'GET_PERMISSIONS',
  GET_PERMISSIONS_ID: 'GET_PERMISSIONS_ID',
  GET_PERMISSIONS_PAGINATION: 'GET_PERMISSIONS_PAGINATION',
  EDIT_PERMISSIONS: 'EDIT_PERMISSIONS',
  CREATE_PERMISSIONS: 'CREATE_PERMISSIONS',
  DELETE_PERMISSIONS: 'DELETE_PERMISSIONS'
};
