export const actionTypes = {
  SET_CEP: "SET_CEP",
  SET_ADDRESS_BY_CEP: "SET_ADDRESS_BY_CEP",
  SET_ADDRESS: "SET_ADDRESS",
  SET_USER_ADDRESS: "SET_USER_ADDRESS",
  SET_GEOLOCATION: "SET_GEOLOCATION",
};
