export const actionTypes = {
  GET_USERS: 'GET_USERS',
  GET_USERS_ID: 'GET_USERS_ID',
  GET_USERS_PAGINATION: 'GET_USERS_PAGINATION',
  EDIT_USERS: 'EDIT_USERS',
  CREATE_USERS: 'CREATE_USERS',
  DELETE_USERS: 'DELETE_USERS',
  APPLY_ROLE_TO_USER: 'APPLY_ROLE_TO_USER'
};
