export const actionTypes = {
  GET_ALL_ROLES: 'GET_ALL_ROLES',
  GET_ROLES: 'GET_ROLES',
  GET_ROLES_ID: 'GET_ROLES_ID',
  GET_ROLES_PAGINATION: 'GET_ROLES_PAGINATION',
  EDIT_ROLES: 'EDIT_ROLES',
  CREATE_ROLES: 'CREATE_ROLES',
  DELETE_ROLES: 'DELETE_ROLES'
};
