export const actionTypes = {
  GET_ALL_CONDUCTORS: 'GET_ALL_CONDUCTORS',
  GET_CONDUCTORS: 'GET_CONDUCTORS',
  GET_CONDUCTORS_ID: 'GET_CONDUCTORS_ID',
  GET_CONDUCTORS_PAGINATION: 'GET_CONDUCTORS_PAGINATION',
  EDIT_CONDUCTORS: 'EDIT_CONDUCTORS',
  CREATE_CONDUCTORS: 'CREATE_CONDUCTORS',
  DELETE_CONDUCTORS: 'DELETE_CONDUCTORS'
};
