export const actionTypes = {
  SET_LOGIN: "SET_LOGIN",
  SET_ACCESS_USER: "SET_ACCESS_USER",
  SET_USER: "SET_USER",
  SET_REQUIRED: "SET_REQUIRED",
  SET_SIGN_UP: "SET_SIGN_UP",
  SET_METHOD_LOGIN: "SET_METHOD_LOGIN",
  SET_ACCESS_PERMISSIONS: "SET_ACCESS_PERMISSIONS",
};
